# Generated by Django 5.1.6 on 2025-02-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('show', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=50)),
                ('is_main', models.BooleanField(default=True)),
                ('release_year', models.IntegerField()),
                ('still_airing', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
