# Generated by Django 5.1.6 on 2025-02-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartooncharacter',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
