# Generated by Django 5.1.6 on 2025-02-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='excluded_characters_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='excluded_shows_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='excluded_characters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='excluded_shows',
            field=models.TextField(blank=True, null=True),
        ),
    ]
