# Generated by Django 5.1.6 on 2025-02-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_cartooncharacter_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitter_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
