# Generated by Django 5.1.6 on 2025-02-28 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_add_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartooncharacter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartooncharacter',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.show'),
        ),
        migrations.AlterField(
            model_name='cartoonsuggestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='excluded_characters',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='excluded_shows',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='excluded_characters',
            field=models.ManyToManyField(blank=True, to='game.cartooncharacter'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='excluded_shows',
            field=models.ManyToManyField(blank=True, to='game.show'),
        ),
    ]
