# Generated by Django 5.1.6 on 2025-02-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_cartoonsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartooncharacter',
            name='image_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
    ]
