# Generated by Django 5.1.6 on 2025-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='excluded_characters',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='excluded_shows',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='excluded_characters',
            field=models.ManyToManyField(blank=True, to='game.cartooncharacter'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='excluded_shows',
            field=models.ManyToManyField(blank=True, to='game.show'),
        ),
    ]
