# Generated by Django 5.1.6 on 2025-03-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_cartooncharacter_name_alter_show_name'),
        ('game', '0005_remove_cartooncharacter_network_and_more'),
    ]

    operations = [
    ]
