# Generated by Django 5.1.6 on 2025-03-02 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_merge_20250302_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoonsuggestion',
            name='name',
        ),
        migrations.AddField(
            model_name='cartoonsuggestion',
            name='character_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartoonsuggestion',
            name='existing_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.show'),
        ),
        migrations.AddField(
            model_name='cartoonsuggestion',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cartoonsuggestion',
            name='show_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartoonsuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('show', 'New Show'), ('character', 'Missing Character'), ('feedback', 'Site Feedback')], default='show', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
