# Generated by Django 5.1.6 on 2025-02-27 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_show_remove_userpreference_excluded_characters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartooncharacter',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
