# Generated by Django 5.1.6 on 2025-02-27 21:27

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    UserPreference = apps.get_model('game', 'UserPreference')
    Show = apps.get_model('game', 'Show')
    CartoonCharacter = apps.get_model('game', 'CartoonCharacter')
    
    for pref in UserPreference.objects.all():
        # Migrate excluded_shows (TextField) to excluded_shows_m2m
        if pref.excluded_shows:
            show_names = [s.strip() for s in pref.excluded_shows.split(',') if s.strip()]
            for name in show_names:
                show, _ = Show.objects.get_or_create(name=name)
                pref.excluded_shows_m2m.add(show)
        
        # Migrate excluded_characters (TextField) to excluded_characters_m2m
        if pref.excluded_characters:
            char_names = [c.strip() for c in pref.excluded_characters.split(',') if c.strip()]
            for name in char_names:
                char = CartoonCharacter.objects.filter(name=name).first()
                if char:
                    pref.excluded_characters_m2m.add(char)

        # Clear old TextFields after migration
        pref.excluded_shows = None
        pref.excluded_characters = None
        pref.save()

def backwards_func(apps, schema_editor):
    UserPreference = apps.get_model('game', 'UserPreference')
    for pref in UserPreference.objects.all():
        pref.excluded_shows = ','.join(pref.excluded_shows_m2m.values_list('name', flat=True))
        pref.excluded_characters = ','.join(pref.excluded_characters_m2m.values_list('name', flat=True))
        pref.save()

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_cartooncharacter_show_alter_show_name'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
        migrations.RemoveField(model_name='userpreference', name='excluded_shows'),
        migrations.RemoveField(model_name='userpreference', name='excluded_characters'),
        migrations.RenameField(model_name='userpreference', old_name='excluded_shows_m2m', new_name='excluded_shows'),
        migrations.RenameField(model_name='userpreference', old_name='excluded_characters_m2m', new_name='excluded_characters'),
    ]
