# Generated by Django 5.1.6 on 2025-03-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_clear_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
