# Generated by Django 5.1.6 on 2025-03-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_userpreference_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartooncharacter',
            name='image_restricted',
            field=models.BooleanField(default=False, help_text='Check if the image cannot be loaded due to server restrictions.'),
        ),
    ]
